name: 'Trivy Container Scan'
description: 'Runs Trivy container vulnerability scan'

inputs:
  image-name:
    description: 'Docker image name to scan with Trivy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Verify Trivy installation
      run: |
        if ! command -v trivy &> /dev/null; then
          echo "❌ Trivy not found. Installing..."
          wget -qO - https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.49.1_Linux-64bit.deb || sudo apt-get install -f -y
        fi
        trivy --version
      shell: bash

    - name: Trivy Container Scan
      run: |
        echo "Scanning Docker image: ${{ inputs.image-name }}"
        
        # Run scan and capture output
        scan_output=$(trivy image --severity HIGH,CRITICAL --exit-code 0 --format table ${{ inputs.image-name }} 2>&1)
        echo "$scan_output"
        
        # Check for critical vulnerabilities specifically
        if echo "$scan_output" | grep -q "CRITICAL"; then
          echo "❌ CRITICAL vulnerabilities found!"
          exit 1
        fi
        
        if echo "$scan_output" | grep -q "HIGH"; then
          echo "❌ HIGH severity vulnerabilities found!"
          exit 1
        fi
        
        echo "✅ No critical vulnerabilities found"
      shell: bash
