name: 'Trivy Container Scan'
description: 'Scans a Docker image for vulnerabilities using Trivy.'

inputs:
  image-name:
    description: 'The name and tag of the Docker image to scan'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Docker Login
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_REGISTRY }} \
          --username ${{ secrets.HARBOR_USERNAME }} \
          --password-stdin
      shell: bash

    - name: Run Trivy Scan
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: ${{ inputs.image-name }}
        format: 'table'
        severity: 'HIGH,CRITICAL'
        exit-code: '1'   # ❌ Fail if HIGH/CRITICAL issues are found
