name: 'Trivy Container Scan'
description: 'Runs Trivy container vulnerability scan and fails on HIGH,CRITICAL vulnerabilities.'

inputs:
  image-name:
    description: 'Docker image name to scan with Trivy'
    required: true
  severity-level:
    description: 'Comma-separated list of severities to fail the build on.'
    required: false
    default: 'CRITICAL,HIGH'

runs:
  using: 'composite'
  steps:
    - name: Scan image with Trivy
      shell: bash
      run: |
        echo "🔍 Scanning Docker image: ${{ inputs.image-name }}"
        echo "🔎 Severity threshold: ${{ inputs.severity-level }}"
        
        # Run Trivy with specified severity level and exit code 1 to fail on vulnerabilities
        trivy image \
          --format table \
          --severity ${{ inputs.severity-level }} \
          --exit-code 1 \
          --quiet \
          "${{ inputs.image-name }}"

        echo "✅ No ${{ inputs.severity-level }} vulnerabilities found!"
      env:
        # Essential for scanning images from private registries like Harbor
        TRIVY_USERNAME: ${{ secrets.HARBOR_USERNAME }}
        TRIVY_PASSWORD: ${{ secrets.HARBOR_PASSWORD }}
        TRIVY_NON_SSL: false
        TRIVY_INSECURE: false
