# .github/actions/trivy-scan/action.yaml

name: 'Trivy Container Scan'
description: 'Scans a Docker image for vulnerabilities using Trivy.'

inputs:
  image-name:
    description: 'The name and tag of the Docker image to scan'
    required: true
  harbor-username:
    description: 'Harbor registry username'
    required: true
  harbor-password:
    description: 'Harbor registry password'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Trivy Container Scan
      run: |
        docker login ${{ secrets.HARBOR_REGISTRY }} --username ${{ inputs.harbor-username }} --password ${{ inputs.harbor-password }}
        trivy image --severity=HIGH,CRITICAL ${{ inputs.image-name }}
      shell: bash
