name: 'Trivy Security Scan'
description: 'Centralized Trivy security scanning for filesystem and container images'

inputs:
  scan-type:
    description: 'Type of scan (fs or image)'
    required: true
    default: 'fs'
  scan-ref:
    description: 'What to scan (directory path or image name)'
    required: true
    default: '.'
  severity:
    description: 'Severity levels to check'
    required: true
    default: 'CRITICAL,HIGH'
  scanners:
    description: 'Scanners to use'
    required: true
    default: 'vuln,secret,config'
  ignore-unfixed:
    description: 'Ignore unfixed vulnerabilities'
    required: false
    default: 'false'
  exit-code:
    description: 'Exit code on vulnerability detection'
    required: false
    default: '1'
  exit-on-eosl:
    description: 'Exit with error code on EOSL (End of Service Life) OS'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Run Trivy scan
      shell: bash
      run: |
        SCAN_TYPE="${{ inputs['scan-type'] }}"
        SCAN_REF="${{ inputs['scan-ref'] }}"
        SEVERITY="${{ inputs['severity'] }}"
        SCANNERS="${{ inputs['scanners'] }}"
        IGNORE_UNFIXED="${{ inputs['ignore-unfixed'] }}"
        EXIT_CODE="${{ inputs['exit-code'] }}"
        EXIT_ON_EOSL="${{ inputs['exit-on-eosl'] }}"

        echo "Running Trivy $SCAN_TYPE scan on: $SCAN_REF"
        echo "Severity: $SEVERITY"
        echo "Scanners: $SCANNERS"
        echo "Exit Code on vuln: $EXIT_CODE"

        # Build command with conditional flags
        CMD="trivy $SCAN_TYPE \"$SCAN_REF\" \
          --format table \
          --severity \"$SEVERITY\" \
          --scanners \"$SCANNERS\" \
          --exit-code \"$EXIT_CODE\" \
          --no-progress"

        # Add optional flags
        if [ "$IGNORE_UNFIXED" = "true" ]; then
          CMD="$CMD --ignore-unfixed"
        fi
        
        if [ "$EXIT_ON_EOSL" = "true" ]; then
          CMD="$CMD --exit-on-eosl"
        fi

        # Execute the command
        eval $CMD
