name: 'Trivy Security Scan'
description: 'Centralized Trivy container security scanning'

inputs:
  image-name:
    description: 'Container image to scan'
    required: true
  severity-threshold:
    description: 'Severity threshold to fail on'
    required: false
    default: 'CRITICAL'
  fail-on-vulnerabilities:
    description: 'Fail on vulnerabilities'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Trivy
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    - name: Run Trivy Scan
      shell: bash
      run: |
        echo "🔍 Scanning ${{ inputs.image-name }} with Trivy..."
        
        # Run scan with specified severity threshold
        trivy image --severity ${{ inputs.severity-threshold }} "${{ inputs.image-name }}"
        
        echo "✅ Trivy scan completed successfully"
