name: Deploy to Kubernetes
description: "Deploy Docker image to DigitalOcean Kubernetes cluster"

inputs:
  do-token:
    description: "DigitalOcean API token"
    required: true

  cluster-name:
    description: "DigitalOcean Kubernetes cluster name"
    required: true

  namespace:
    description: "Kubernetes namespace"
    required: true

  app-name:
    description: "Application name (e.g., admin, server, website)"
    required: true

  image:
    description: "Docker image with tag"
    required: true

  deployment-file:
    description: "Path to the deployment YAML file"
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up doctl
      uses: cloudops-one/action-doctl@v2
      with:
        token: ${{ inputs.do-token }}

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-name }}
      shell: bash

    - name: Apply Deployment YAML (if provided)
      if: ${{ inputs.deployment-file != '' }}
      run: |
        echo "Applying deployment file ${{ inputs.deployment-file }} to namespace ${{ inputs.namespace }}"
        kubectl apply -f ${{ inputs.deployment-file }} -n ${{ inputs.namespace }}
      shell: bash

    - name: Update Deployment image
      run: |
        DEPLOYMENT_NAME="irai-yoga-v1-${{ inputs.app-name }}-${{ inputs.namespace }}"
        CONTAINER_NAME="irai-yoga-v1-${{ inputs.app-name }}-${{ inputs.namespace }}"
        echo "Updating deployment '$DEPLOYMENT_NAME' container '$CONTAINER_NAME' to image '${{ inputs.image }}' in namespace '${{ inputs.namespace }}'"
        kubectl rollout status deployment/$DEPLOYMENT_NAME -n ${{ inputs.namespace }}
      shell: bash
