name: 'SonarQube Scan'
description: 'SonarQube code quality scanning for Backend'

inputs:
  sonar-token:
    description: 'SonarQube token'
    required: true
  sonar-host-url:
    description: 'SonarQube host URL'
    required: true
  project-key:
    description: 'SonarQube project key'
    required: true
  project-name:
    description: 'SonarQube project name'
    required: true
  docker-tag:
    description: 'Docker tag for project version'
    required: true
  branch-name:
    description: 'Git branch name'
    required: true
  sources-path:
    description: 'Path to source code'
    default: 'src'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Make gradlew executable
      shell: bash
      run: |
        chmod +x ./gradlew

    - name: Format code with Spotless
      shell: bash
      run: |
        ./gradlew spotlessApply --no-daemon

    - name: Build and test with coverage
      shell: bash
      run: |
        ./gradlew clean test jacocoTestReport --no-daemon

    - name: Verify coverage report exists
      shell: bash
      run: |
        if [ -f "build/reports/jacoco/test/jacocoTestReport.xml" ]; then
          echo "✅ JaCoCo report found"
          echo "Report location: build/reports/jacoco/test/jacocoTestReport.xml"
        else
          echo "❌ JaCoCo report missing"
          find build -name "jacocoTestReport.xml" || echo "No jacoco report found"
          exit 1
        fi

    - name: Run SonarQube analysis
      shell: bash
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
      run: |
        ./gradlew sonar \
          -Dsonar.branch.name="${{ inputs.branch-name }}" \
          -Dsonar.projectVersion="${{ inputs.docker-tag }}" \
          --no-daemon

    - name: Analysis summary
      shell: bash
      run: |
        echo "=== SonarQube Analysis Complete ==="
        echo "Project: ${{ inputs.project-name }}"
        echo "Key: ${{ inputs.project-key }}"
        echo "Version: ${{ inputs.docker-tag }}"
        echo "Branch: ${{ inputs.branch-name }}"
        echo "================================"
