name: 'SonarQube Scan'
description: 'SonarQube code quality scanning'

inputs:
  sonar-token:
    required: true
    description: 'SonarQube token'
  sonar-host-url:
    required: true
    description: 'SonarQube server URL'
  project-key:
    required: true
    description: 'SonarQube project key'
  project-name:
    required: true
    description: 'SonarQube project name'
  docker-tag:
    required: true
    description: 'Docker tag for version'
  branch-name:
    required: true
    description: 'Git branch name'
  sources-path:
    default: 'src'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: cloudops-one/checkout@v4

    - name: Setup Java
      uses: cloudops-one/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Run SonarQube Scan
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
      run: |
        chmod +x ./gradlew
        ./gradlew sonar \
          -Dsonar.projectKey="${{ inputs.project-key }}" \
          -Dsonar.projectName="${{ inputs.project-name }}" \
          -Dsonar.projectVersion="${{ inputs.docker-tag }}" \
          --no-daemon
      shell: bash
