name: 'SonarQube Scan'
description: 'Enhanced SonarQube code quality scanning with full Gradle compatibility'

inputs:
  sonar-token:
    required: true
  sonar-host-url:
    required: true
  project-key:
    required: true
  project-name:
    required: true
  docker-tag:
    required: true
  branch-name:
    required: true
  sources-path:
    default: 'src'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: cloudops-one/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 21
      uses: cloudops-one/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Grant execute permissions for Gradle
      run: chmod +x ./gradlew
      shell: bash

    # Add this step to apply formatting fixes automatically
    - name: Apply Spotless Formatting
      run: ./gradlew spotlessApply --no-daemon
      shell: bash

    - name: Clean and Build (compile + test + coverage)
      run: ./gradlew clean build jacocoTestReport --no-daemon --stacktrace
      shell: bash

    - name: Verify JaCoCo Report
      run: |
        if [ -f "build/reports/jacoco/test/jacocoTestReport.xml" ]; then
          echo "✅ JaCoCo report found"
        else
          echo "❌ JaCoCo report missing"
          exit 1
        fi
      shell: bash

    - name: SonarQube Scan
      env:
        SONAR_TOKEN: ${{ inputs.sonar-token }}
        SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
      run: |
        ./gradlew sonar \
          -Dsonar.projectKey="${{ inputs.project-key }}" \
          -Dsonar.projectName="${{ inputs.project-name }}" \
          -Dsonar.projectVersion="${{ inputs.docker-tag }}" \
          -Dsonar.branch.name="${{ inputs.branch-name }}" \
          --no-daemon --stacktrace --info
      shell: bash

    - name: Summary
      run: |
        echo "=== ✅ SonarQube Scan Complete ==="
        echo "Project: ${{ inputs.project-name }}"
        echo "Key: ${{ inputs.project-key }}"
        echo "Branch: ${{ inputs.branch-name }}"
        echo "Version: ${{ inputs.docker-tag }}"
      shell: bash
