name: "Centralized Docker Operations"
description: "Builds and pushes Docker images to Harbor for any component"

inputs:
  harbor-registry:
    description: "Harbor registry URL"
    required: true
  harbor-username:
    description: "Harbor username"
    required: true
  harbor-password:
    description: "Harbor password"
    required: true
  project-name:
    description: "Project name"
    required: true
  component:
    description: "Component name (frontend, backend, api, etc.)"
    required: true
  docker-tag:
    description: "Docker tag"
    required: true
  dockerfile-path:
    description: "Path to Dockerfile directory"
    required: false
    default: "."
  context-path:
    description: "Build context path"
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      run: |
        if [ -z "${{ inputs.harbor-registry }}" ]; then
          echo "Error: harbor-registry is empty"
          exit 1
        fi
        if [ -z "${{ inputs.harbor-username }}" ]; then
          echo "Error: harbor-username is empty"
          exit 1
        fi
        if [ -z "${{ inputs.harbor-password }}" ]; then
          echo "Error: harbor-password is empty"
          exit 1
        fi
      shell: bash

    - name: Log in to Harbor
      run: |
        echo "Logging into Harbor registry: ${{ inputs.harbor-registry }}"
        echo "${{ inputs.harbor-password }}" | \
        docker login -u "${{ inputs.harbor-username }}" \
        --password-stdin "${{ inputs.harbor-registry }}"
      shell: bash

    - name: Build Docker Image for ${{ inputs.component }}
      run: |
        echo "Building image: ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}"
        docker build \
          -t ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }} \
          -f ${{ inputs.dockerfile-path }}/Dockerfile \
          ${{ inputs.context-path }}
      shell: bash

    - name: Push ${{ inputs.component }} Image to Harbor
      run: |
        echo "Pushing image to Harbor..."
        docker push ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}
      shell: bash

    - name: Log out from Harbor
      run: |
        docker logout "${{ inputs.harbor-registry }}"
        echo "Docker build and push completed successfully!"
      shell: bash
