name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: The name of the Docker image to build.
      registry:
        required: true
        type: string
        description: The Docker registry URL.
      tag:
        required: false
        type: string
        description: A specific tag for the image. If not provided, a default tag is generated.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set_tag
        run: |
          # Use the provided tag, or generate a default one
          if [ -n "${{ inputs.tag }}" ]; then
            TAG="${{ inputs.tag }}"
          else
            # Get the branch name, replace '/' with '-', and convert to lowercase
            BRANCH_NAME=$(echo "${{ github.ref_name }}" | tr '[:upper:]' '[:lower:]' | sed 's/\//-/g')
            # Get the short commit SHA
            SHA_SHORT=$(echo "${{ github.sha }}" | cut -c1-7)
            TAG="${BRANCH_NAME}-${SHA_SHORT}"
          fi
          echo "Generated tag: $TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.registry }}/${{ inputs.image_name }}:${{ steps.set_tag.outputs.tag }}
