name: 'Docker Operations'
description: 'Builds and pushes a Docker image to a specified registry with a given tag.'
inputs:
  project-name:
    required: true
    type: string
    description: The name of the project.
  component:
    required: true
    type: string
    description: The name of the component.
  harbor-registry:
    required: true
    type: string
    description: The Harbor registry URL.
  docker-tag:
    required: true
    type: string
    description: A specific tag for the image.
  harbor-username:
    required: true
    description: The username for the Harbor registry.
  harbor-password:
    required: true
    description: The password for the Harbor registry.

runs:
  using: 'composite'
  steps:
    - name: Log in to Docker Registry
      run: |
        echo "${{ inputs.harbor-password }}" | docker login ${{ inputs.harbor-registry }} --username ${{ inputs.harbor-username }} --password-stdin
      shell: bash

    - name: Build and Tag Docker Image
      run: |
        docker build -t ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }} .
      shell: bash
    
    - name: Push Docker Image
      run: |
        docker push ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}
      shell: bash

    - name: Log out from Docker Registry
      if: always()
      run: |
        docker logout ${{ inputs.harbor-registry }}
      shell: bash
