name: 'Docker Operations'
description: 'Builds and pushes a Docker image to a specified registry with a given tag.'
inputs:
  project-name:
    required: true
    type: string
    description: The name of the project.
  component:
    required: true
    type: string
    description: The name of the component.
  harbor-registry:
    required: true
    type: string
    description: The Harbor registry URL.
  docker-tag:
    required: true
    type: string
    description: A specific tag for the image.
  harbor-username:
    required: true
    description: The username for the Harbor registry.
  harbor-password:
    required: true
    description: The password for the Harbor registry.

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.harbor-registry }}
        username: ${{ inputs.harbor-username }}
        password: ${{ inputs.harbor-password }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}
