name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      project-name:
        required: true
        type: string
        description: The name of the project.
      component:
        required: true
        type: string
        description: The name of the component.
      harbor-registry:
        required: true
        type: string
        description: The Harbor registry URL.
      docker-tag:
        required: true
        type: string
        description: A specific tag for the image.
    secrets:
      harbor-username:
        required: true
        description: The username for the Harbor registry.
      harbor-password:
        required: true
        description: The password for the Harbor registry.

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: cloudops-one/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ inputs.harbor-registry }}
          username: ${{ secrets.harbor-username }}
          password: ${{ secrets.harbor-password }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}
