name: 'Snyk Security Scan'
description: 'Centralized Snyk container security scanning'

inputs:
  image-name:
    description: 'Container image to scan'
    required: true
  snyk-token:
    description: 'Snyk authentication token'
    required: true
  severity-threshold:
    description: 'Severity threshold to fail on'
    required: false
    default: 'high'
  fail-on-vulnerabilities:
    description: 'Fail on vulnerabilities'
    required: false
    default: 'true'

runs:
  using: 'composite'
  steps:
    - name: Install Snyk
      shell: bash
      run: |
        npm install -g snyk

    - name: Run Snyk Scan
      shell: bash
      run: |
        echo "🔍 Scanning ${{ inputs.image-name }} with Snyk..."
        
        # Authenticate with Snyk
        echo "${{ inputs.snyk-token }}" | snyk auth
        
        # Run Snyk container scan
        snyk container test "${{ inputs.image-name }}" --severity-threshold=${{ inputs.severity-threshold }}
        
        echo "✅ Snyk scan completed successfully"
