name: 'Snyk Container Scan'
description: 'Runs Snyk container security scanning with display name formatting'

inputs:
  image-name:
    description: 'Full Docker image name with tag to scan'
    required: true
  snyk-token:
    description: 'Snyk API token'
    required: true
  severity-threshold:
    description: 'Severity threshold for failing the scan'
    required: false
    default: 'high'

runs:
  using: 'composite'
  steps:
    - name: Install Snyk CLI
      run: |
        npm install -g snyk
      shell: bash

    - name: Authenticate Snyk
      run: |
        snyk auth ${{ inputs.snyk-token }}
        echo "✅ Snyk authenticated successfully"
      shell: bash

    - name: Run Snyk Container Scan
      run: |
        echo "Running Snyk container scan on: ${{ inputs.image-name }}"
        
        # Extract just the image name without registry for display
        IMAGE_NAME=$(echo "${{ inputs.image-name }}" | cut -d'/' -f2- | cut -d':' -f1)
        echo "Using display name: $IMAGE_NAME"
        
        # Scan with custom display name
        snyk container test "${{ inputs.image-name }}" \
          --severity-threshold=${{ inputs.severity-threshold }} \
          --app-vulns="$IMAGE_NAME"
        
        # Monitor with custom name
        snyk container monitor "${{ inputs.image-name }}" \
          --app-vulns="$IMAGE_NAME"
        
        echo "✅ Snyk container scan completed"
      shell: bash
