name: 'Snyk Security Scan'
description: 'Runs Snyk dependency vulnerability scan'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'

runs:
  using: 'composite'
  steps:
    - name: Check for package.json
      run: |
        if [ ! -f "package.json" ]; then
          echo "ℹ️ No package.json found. Skipping Snyk scan."
          exit 0
        fi
      shell: bash

    - name: Setup Node.js
      uses: cloudops-one/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: |
        # Try multiple lock files with fallbacks
        if [ -f "package-lock.json" ]; then
          npm ci --no-audit --no-fund
        elif [ -f "yarn.lock" ]; then
          npm install -g yarn
          yarn install --frozen-lockfile --ignore-engines
        elif [ -f "pnpm-lock.yaml" ]; then
          npm install -g pnpm
          pnpm install --frozen-lockfile
        else
          npm install --no-audit --no-fund
        fi
      shell: bash

    - name: Run Snyk scan
      run: |
        snyk auth ${{ inputs.snyk-token }}
        echo "Running Snyk dependency scan..."
        
        # Run Snyk but don't fail the build immediately
        snyk test --all-projects --severity-threshold=high || \
          echo "⚠️ Snyk found vulnerabilities, but continuing pipeline..."
        
        echo "Monitoring project in Snyk dashboard..."
        snyk monitor --all-projects
        echo "✅ Snyk scan completed"
      shell: bash
