# .github/actions/snyk-scan/action.yaml (Refined Snyk action)
name: 'Snyk Security Scan'
description: 'Runs Snyk dependency and container vulnerability scan'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true
  node-version:
    description: 'Node.js version'
    required: false
    default: '20'
  target:
    description: 'The Snyk command to run (e.g., test or monitor)'
    required: true
    default: 'test'
  project-path:
    description: 'Path to the project to scan'
    required: false
    default: '.'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install Snyk CLI
      run: npm install -g snyk
      shell: bash

    - name: Install Dependencies
      run: |
        if [ -f "package-lock.json" ]; then
          npm ci --no-audit --no-fund
        elif [ -f "yarn.lock" ]; then
          npm install -g yarn
          yarn install --frozen-lockfile --ignore-engines
        else
          echo "No lock file found. Running npm install."
          npm install --no-audit --no-fund
        fi
      working-directory: ${{ inputs.project-path }}
      shell: bash

    - name: Authenticate Snyk
      run: snyk auth ${{ inputs.snyk-token }}
      shell: bash

    - name: Run Snyk scan
      if: ${{ inputs.target == 'test' }}
      run: |
        snyk test --all-projects --severity-threshold=high
      shell: bash

    - name: Run Snyk monitor
      if: ${{ inputs.target == 'monitor' }}
      run: |
        snyk monitor --all-projects
      shell: bash
