name: 'Security Scan'
description: 'Runs security scans using Snyk and Trivy'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Snyk Security Scan
      uses: snyk/actions/node@master
      with:
        args: --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}

    - name: Trivy Vulnerability Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'your-image'
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy Results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'
