name: 'Security Scan'
description: 'Runs security scans using Snyk and Trivy'

inputs:
  snyk-token:
    description: 'Snyk API token'
    required: true
  image-ref:
    description: 'Image reference for Trivy scan'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Snyk Scan
      uses: cloudops-one/node@master
      with:
        args: test

    - name: Trivy Scan
      uses: cloudops-one/trivy-action@master
      with:
        image-ref: ${{ inputs.image-ref }}

    - name: Upload SARIF to GitHub
      uses: cloudops-one/upload-sarif@v3
      with:
        sarif_file: results.sarif
