name: 'Setup Environment'
description: 'Sets up environment variables and determines deployment context'

inputs:
  github_ref:
    description: 'The GitHub ref that triggered the workflow'
    required: true

outputs:
  environment:
    description: 'The determined environment (preview, stage, live)'
    value: ${{ steps.env.outputs.environment }}
  docker_tag:
    description: 'The determined Docker tag'
    value: ${{ steps.tag.outputs.docker_tag }}

runs:
  using: 'composite'
  steps:
    - name: Determine environment and tag
      id: env
      shell: bash
      run: |
        if [[ "${{ inputs.github_ref }}" == refs/tags/* ]]; then
          echo "environment=live" >> $GITHUB_OUTPUT
          TAG="${GITHUB_REF#refs/tags/}"
          echo "docker_tag=$TAG" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.github_ref }}" == refs/heads/main ]]; then
          echo "environment=stage" >> $GITHUB_OUTPUT
          echo "docker_tag=stage" >> $GITHUB_OUTPUT
        else
          echo "environment=preview" >> $GITHUB_OUTPUT
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          SANITIZED_BRANCH=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9-]/-/g' | tr '[:upper:]' '[:lower:]')
          echo "docker_tag=$SANITIZED_BRANCH" >> $GITHUB_OUTPUT
        fi
