name: Deploy to Kubernetes
description: "Deploy Docker image to DigitalOcean Kubernetes cluster"

inputs:
  do-token:
    description: "DigitalOcean API token"
    required: true
  cluster-name:
    description: "DigitalOcean Kubernetes cluster name"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: true
    default: "irai-yoga-v1-live"
  deployment-name:
    description: "Deployment name"
    required: true
    default: "irai-yoga-v1-admin-live"
  container-name:
    description: "Container name"
    required: true
    default: "irai-yoga-v1-admin-live"
  image:
    description: "Docker image with tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ inputs.do-token }}

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-name }}
      shell: bash

    - name: Deploy to Kubernetes
      run: |
        echo "Deploying image '${{ inputs.image }}' to deployment '${{ inputs.deployment-name }}' in namespace '${{ inputs.namespace }}'"
        kubectl set image deployment/${{ inputs.deployment-name }} ${{ inputs.container-name }}=${{ inputs.image }} -n ${{ inputs.namespace }}
        kubectl rollout status deployment/${{ inputs.deployment-name }} -n ${{ inputs.namespace }}
      shell: bash
