name: k8s-deployment
description: Deploy admin, server, and website to Kubernetes

inputs:
  namespace:
    required: true
    description: Target namespace
  kubeconfig:
    required: true
    description: Kubeconfig content
  admin-image:
    required: true
    description: Docker image for admin
  server-image:
    required: true
    description: Docker image for server
  website-image:
    required: true
    description: Docker image for website

runs:
  using: "composite"
  steps:
    - name: Setup Kubeconfig
      run: |
        echo "${{ inputs.kubeconfig }}" > kubeconfig.yaml
        export KUBECONFIG=$(pwd)/kubeconfig.yaml
      shell: bash

    - name: Create namespace if not exists
      run: |
        kubectl get ns ${{ inputs.namespace }} || kubectl create ns ${{ inputs.namespace }}
      shell: bash

    - name: Deploy Admin
      run: |
        kubectl set image deployment/irai-yoga-v1-admin ${{ inputs.namespace }} ${{ inputs.admin-image }} -n ${{ inputs.namespace }} || \
        kubectl apply -f ./k8s/admin-deployment.yaml -n ${{ inputs.namespace }}
      shell: bash

    - name: Deploy Server
      run: |
        kubectl set image deployment/irai-yoga-v1-server ${{ inputs.namespace }} ${{ inputs.server-image }} -n ${{ inputs.namespace }} || \
        kubectl apply -f ./k8s/server-deployment.yaml -n ${{ inputs.namespace }}
      shell: bash

    - name: Deploy Website
      run: |
        kubectl set image deployment/irai-yoga-v1-website ${{ inputs.namespace }} ${{ inputs.website-image }} -n ${{ inputs.namespace }} || \
        kubectl apply -f ./k8s/website-deployment.yaml -n ${{ inputs.namespace }}
      shell: bash
