inputs:
  cluster-name:
    description: "Name of the DigitalOcean Kubernetes cluster"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: true
    default: "irai-yoga-v1-live"
  deployment-name:
    description: "Kubernetes deployment name"
    required: true
    default: "irai-yoga-v1-admin-live"
  container-name:
    description: "Container name in the deployment"
    required: true
    default: "irai-yoga-v1-admin-live"
  image:
    description: "Full Docker image URL with tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up doctl
      uses: cloudops-one/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN }}

    - name: Save kubeconfig
      run: |
        doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-name }}

    - name: Deploy to Kubernetes
      run: |
        echo "Deploying image '${{ inputs.image }}' to deployment '${{ inputs.deployment-name }}' in namespace '${{ inputs.namespace }}'"
        kubectl set image deployment/${{ inputs.deployment-name }} ${{ inputs.container-name }}=${{ inputs.image }} -n ${{ inputs.namespace }}
        kubectl rollout status deployment/${{ inputs.deployment-name }} -n ${{ inputs.namespace }}
