name: "Kubernetes Deployment"
description: "Deploys applications to Kubernetes cluster"

inputs:
  namespace:
    description: "Kubernetes namespace"
    required: true
  kubeconfig:
    description: "Kubeconfig file content"
    required: true
  admin-image:
    description: "Admin Docker image"
    required: true
  server-image:
    description: "Server Docker image"
    required: true
  website-image:
    description: "Website Docker image"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install kubectl
      run: |
        KUBECTL_VERSION=$(curl -s https://dl.k8s.io/release/stable.txt)
        curl -LO "https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client
      shell: bash

    - name: Configure Kubeconfig
      run: |
        echo "${{ inputs.kubeconfig }}" > kubeconfig.yaml
        export KUBECONFIG=$PWD/kubeconfig.yaml
      shell: bash

    - name: Ensure Namespace Exists
      run: |
        kubectl get ns ${{ inputs.namespace }} || kubectl create ns ${{ inputs.namespace }}
      shell: bash

    - name: Deploy Admin
      run: |
        kubectl -n ${{ inputs.namespace }} set image deployment/irai-yoga-admin admin=${{ inputs.admin-image }} --record || \
        kubectl -n ${{ inputs.namespace }} create deployment irai-yoga-admin --image=${{ inputs.admin-image }}
      shell: bash

    - name: Deploy Server
      run: |
        kubectl -n ${{ inputs.namespace }} set image deployment/irai-yoga-server server=${{ inputs.server-image }} --record || \
        kubectl -n ${{ inputs.namespace }} create deployment irai-yoga-server --image=${{ inputs.server-image }}
      shell: bash

    - name: Deploy Website
      run: |
        kubectl -n ${{ inputs.namespace }} set image deployment/irai-yoga-website website=${{ inputs.website-image }} --record || \
        kubectl -n ${{ inputs.namespace }} create deployment irai-yoga-website --image=${{ inputs.website-image }}
      shell: bash
