name: Deploy Kubernetes Apps

description: Centralized deployment action for all apps (admin, server, website)

inputs:
  namespace:
    description: 'Namespace to deploy into'
    required: true
  admin-image:
    description: 'Docker image for Admin app'
    required: true
  server-image:
    description: 'Docker image for Server app'
    required: true
  website-image:
    description: 'Docker image for Website app'
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG }}" > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig

    - name: Deploy Admin
      run: |
        echo "Deploying Admin to namespace: ${{ inputs.namespace }}"
        kubectl -n ${{ inputs.namespace }} set image deployment/admin admin=${{ inputs.admin-image }} --record
        kubectl -n ${{ inputs.namespace }} rollout status deployment/admin

    - name: Deploy Server
      run: |
        echo "Deploying Server to namespace: ${{ inputs.namespace }}"
        kubectl -n ${{ inputs.namespace }} set image deployment/server server=${{ inputs.server-image }} --record
        kubectl -n ${{ inputs.namespace }} rollout status deployment/server

    - name: Deploy Website
      run: |
        echo "Deploying Website to namespace: ${{ inputs.namespace }}"
        kubectl -n ${{ inputs.namespace }} set image deployment/website website=${{ inputs.website-image }} --record
        kubectl -n ${{ inputs.namespace }} rollout status deployment/website
