name: Deploy to Kubernetes
description: "Deploy to DigitalOcean Kubernetes cluster using deployment YAML"

inputs:
  do-token:
    description: "DigitalOcean API token"
    required: true
  cluster-name:
    description: "DigitalOcean Kubernetes cluster name"
    required: true
  namespace:
    description: "Kubernetes namespace"
    required: true
  deployment-file:
    description: "Path to the deployment YAML file"
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up doctl
      uses: cloudops-one/action-doctl@v2
      with:
        token: ${{ inputs.do-token }}

    - name: Save kubeconfig
      run: doctl kubernetes cluster kubeconfig save ${{ inputs.cluster-name }}
      shell: bash

    - name: Apply Deployment YAML
      run: |
        echo "Applying deployment file ${{ inputs.deployment-file }} to namespace ${{ inputs.namespace }}"
        kubectl apply -f ${{ inputs.deployment-file }} -n ${{ inputs.namespace }}
        echo "Waiting for rollout..."
        DEPLOY_NAME=$(yq e '.metadata.name' ${{ inputs.deployment-file }})
        kubectl rollout status deployment/$DEPLOY_NAME -n ${{ inputs.namespace }}
      shell: bash
