name: "Docker Operations"
description: "Builds and pushes Docker images"

inputs:
  operation:
    description: "Operation to perform: build-push"
    required: true
  harbor-registry:
    description: "Harbor registry URL"
    required: true
  harbor-username:
    description: "Harbor username"
    required: true
  harbor-password:
    description: "Harbor password"
    required: true
  project-name:
    description: "Project name"
    required: true
  component:
    description: "Component name"
    required: true
  docker-tag:
    description: "Docker tag"
    required: true

runs:
  using: "composite"
  steps:
    - name: Log in to Harbor
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.harbor-registry }}
        username: ${{ inputs.harbor-username }}
        password: ${{ inputs.harbor-password }}

    - name: Build Docker Image
      run: docker build -t ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }} .

    - name: Push Docker Image
      run: docker push ${{ inputs.harbor-registry }}/${{ inputs.project-name }}/${{ inputs.component }}:${{ inputs.docker-tag }}
