name: 'Test and Coverage'
description: 'Runs tests with coverage and checks thresholds'

inputs:
  node-version:
    description: 'Node.js version'
    required: true
    default: '20'
  threshold-statements:
    description: 'Statements coverage threshold'
    required: false
    default: '80'
  threshold-branches:
    description: 'Branches coverage threshold'
    required: false
    default: '70'
  threshold-functions:
    description: 'Functions coverage threshold'
    required: false
    default: '75'
  threshold-lines:
    description: 'Lines coverage threshold'
    required: false
    default: '80'

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Run tests with coverage
      shell: bash
      run: |
        npx jest --coverage \
          --coverageReporters=text,json,lcov,cobertura \
          --coverageDirectory=./coverage \
          --collectCoverageFrom="src/**/*.{js,jsx,ts,tsx}" \
          --testFailureExitCode=0

    - name: Check coverage thresholds
      shell: bash
      env:
        THRESHOLD_STATEMENTS: ${{ inputs.threshold-statements }}
        THRESHOLD_BRANCHES: ${{ inputs.threshold-branches }}
        THRESHOLD_FUNCTIONS: ${{ inputs.threshold-functions }}
        THRESHOLD_LINES: ${{ inputs.threshold-lines }}
      run: |
        # Your entire threshold check script here
        if [ -f "coverage/coverage-summary.json" ]; then
          echo "📊 Checking coverage thresholds..."
          node -e "
            // ... your full node script ...
          "
        else
          echo "❌ Coverage report not found"
          exit 1
        fi

    - name: Display coverage summary
      shell: bash
      env:
        THRESHOLD_STATEMENTS: ${{ inputs.threshold-statements }}
        THRESHOLD_BRANCHES: ${{ inputs.threshold-branches }}
        THRESHOLD_FUNCTIONS: ${{ inputs.threshold-functions }}
        THRESHOLD_LINES: ${{ inputs.threshold-lines }}
      run: |
        # Your entire display summary script here
        if [ -f "coverage/coverage-summary.json" ]; then
          echo "📊 Coverage Report Summary:"
          echo "=========================="
          node -e "
            // ... your full node script ...
          "
          echo "📈 Thresholds:"
          echo "  Statements: $THRESHOLD_STATEMENTS%"
          echo "  Branches: $THRESHOLD_BRANCHES%"
          echo "  Functions: $THRESHOLD_FUNCTIONS%"
          echo "  Lines: $THRESHOLD_LINES%"
        fi
