name: "Build Java Project"
description: "Builds Java projects with Maven or Gradle"

inputs:
  build-tool:
    description: "Build tool (maven or gradle)"
    required: true
  java-version:
    description: "Java version"
    required: true
  cache:
    description: "Enable caching"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: cloudops-one/checkout@v4

    - name: Setup Java
      uses: cloudops-one/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: ${{ inputs.build-tool }}

    - name: Verify Java installation
      run: |
        java -version
        javac -version
      shell: bash

    - name: Build with Gradle
      if: ${{ inputs.build-tool == 'gradle' }}
      run: ./gradlew build
      shell: bash

    - name: Build with Maven
      if: ${{ inputs.build-tool == 'maven' }}
      run: mvn compile
      shell: bash
