name: 'DNS Management'
description: 'Determines domain configuration based on deployment environment'

inputs:
  github_ref:
    description: 'The GitHub ref that triggered the workflow'
    required: true

outputs:
  domain:
    description: 'The determined domain configuration'
    value: ${{ steps.domain.outputs.domain }}

runs:
  using: 'composite'
  steps:
    - name: Determine domain configuration
      id: domain
      shell: bash
      run: |
        if [[ "${{ inputs.github_ref }}" == refs/tags/* ]]; then
          echo "domain=live-domain-config" >> $GITHUB_OUTPUT
        elif [[ "${{ inputs.github_ref }}" == refs/heads/main ]]; then
          echo "domain=stage-domain-config" >> $GITHUB_OUTPUT
        else
          echo "domain=preview-domain-config" >> $GITHUB_OUTPUT
        fi
