apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
  namespace: irai-yoga-v1-preview
  labels:
    app: SELECTOR_APP_PLACEHOLDER
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SELECTOR_APP_PLACEHOLDER
  template:
    metadata:
      labels:
        app: SELECTOR_APP_PLACEHOLDER
    spec:
      containers:
        - name: SERVER_CONTAINER_PLACEHOLDER
          image: harbor.cloudops.terv.pro/server-irai-yoga/server:TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: preview
            - name: SPRING_CLOUD_VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: irai-yoga-vault-token
                  key: token
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: "500m"
              memory: 1500Mi
      imagePullSecrets:
        - name: harbor-secret
