name: 'Notify'
description: 'Sends deployment notifications to Zoho Cliq'

inputs:
  webhook-url:
    description: 'Zoho Cliq webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
  environment:
    description: 'The environment (preview, stage, live)'
    required: true
  status:
    description: 'Deployment status (success, failure)'
    required: false
    default: 'success'
  service-type:
    description: 'Service type (admin, server, website)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send notification
      shell: bash
      run: |
        # Get current timestamp
        CURRENT_TIME=$(date +'%I:%M %P')
        CURRENT_DATE=$(date +'%b %d, %Y')
        
        # Create SIMPLE text message (no formatting)
        SIMPLE_MESSAGE="${{ inputs.message }} - ${{ inputs.environment }} - $CURRENT_TIME $CURRENT_DATE"
        
        # Create SIMPLE JSON payload (no card, no complex structure)
        JSON_PAYLOAD="{\"text\": \"$SIMPLE_MESSAGE\"}"
        
        echo "Webhook URL: ${{ inputs.webhook-url }}"
        echo "JSON Payload: $JSON_PAYLOAD"
        
        # Send the notification
        curl -X POST "${{ inputs.webhook-url }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          -w "\nHTTP Status: %{http_code}\n" \
          --fail
        
        echo "✅ Notification sent successfully!"
