name: "Zoho Cliq Deployment Notification"
description: "Send Zoho Cliq card notifications for deployment"
inputs:
  message:
    description: "Deployment message text"
    required: true
  environment:
    description: "Environment (preview/stage/live)"
    required: true
  status:
    description: "Deployment status (success/failure)"
    required: true
  service-type:
    description: "Service type (admin/server/website)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send card notification to Zoho Cliq
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/notify.sh
        $GITHUB_ACTION_PATH/notify.sh \
          "${{ inputs.message }}" \
          "${{ inputs.environment }}" \
          "${{ inputs.status }}" \
          "${{ inputs['service-type'] }}"
