name: 'Notify'
description: 'Sends deployment notifications to Zoho Cliq'

inputs:
  webhook-url:
    description: 'Zoho Cliq webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
  environment:
    description: 'The environment (preview, stage, live)'
    required: true
  status:
    description: 'Deployment status (success, failure)'
    required: false
    default: 'success'
  service-type:
    description: 'Service type (admin, server, website)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send notification
      shell: bash
      run: |
        # Determine service URL based on service type and environment
        if [ "${{ inputs.service-type }}" = "admin" ]; then
          SERVICE_NAME="Admin"
          if [ "${{ inputs.environment }}" = "preview" ]; then
            SERVICE_URL="https://admin.preview.v1.irai.yoga"
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            SERVICE_URL="https://admin.stage.v1.irai.yoga"
          else
            SERVICE_URL="https://admin.live.v1.irai.yoga"
          fi
        elif [ "${{ inputs.service-type }}" = "server" ]; then
          SERVICE_NAME="Server"
          if [ "${{ inputs.environment }}" = "preview" ]; then
            SERVICE_URL="https://server.preview.v1.irai.yoga"
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            SERVICE_URL="https://server.stage.v1.irai.yoga"
          else
            SERVICE_URL="https://server.live.v1.irai.yoga"
          fi
        else
          SERVICE_NAME="Website"
          if [ "${{ inputs.environment }}" = "preview" ]; then
            SERVICE_URL="https://website.preview.v1.irai.yoga"
          elif [ "${{ inputs.environment }}" = "stage" ]; then
            SERVICE_URL="https://website.stage.v1.irai.yoga"
          else
            SERVICE_URL="https://irai.yoga"
          fi
        fi

        # Determine title based on status
        if [ "${{ inputs.status }}" = "success" ]; then
          TITLE="$SERVICE_NAME Deployment Successful - ${{ inputs.environment }}"
        else
          TITLE="$SERVICE_NAME Deployment Failed - ${{ inputs.environment }}"
        fi

        # Create simple, clean message without complex formatting
        CURRENT_TIME=$(date +'%I:%M %P')
        CURRENT_DATE=$(date +'%b %d, %Y')
        
        # Build the final message (simple text without markdown)
        FINAL_MESSAGE="${{ inputs.message }}\n\n$SERVICE_NAME: $SERVICE_URL\nTime: $CURRENT_TIME\nDate: $CURRENT_DATE"

        # Create the JSON payload (SIMPLE VERSION - no complex formatting)
        JSON_PAYLOAD="{\"text\": \"$FINAL_MESSAGE\", \"card\": {\"title\": \"$TITLE\", \"theme\": \"basic\", \"thumbnail\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\"}}"

        # Send the notification
        echo "Sending $SERVICE_NAME deployment notification..."
        
        curl -X POST "${{ inputs.webhook-url }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD" \
          -w "\nHTTP Status: %{http_code}\n" \
          --fail

        echo "✅ Notification sent successfully!"
