name: "Zoho Cliq Deployment Notification"
description: "Send Zoho Cliq card notifications for deployment"
inputs:
  message:
    description: "Deployment message text"
    required: true
  environment:
    description: "Environment (preview/stage/live)"
    required: true
  status:
    description: "Deployment status (success/failure)"
    required: true
  service-type:
    description: "Service type (admin/server/website)"
    required: true
  preview-url:
    description: "Dynamic preview URL (required for preview environment)"
    required: false
  stage-url:
    description: "Dynamic stage URL (required for stage environment)"
    required: false
  live-url:
    description: "Dynamic live URL (required for live environment)"
    required: false
  # ✅ ADDED: Webhook URL inputs
  zoho-webhook-preview:
    description: "Zoho webhook URL for preview environment"
    required: true
  zoho-webhook-stage:
    description: "Zoho webhook URL for stage environment"
    required: true
  zoho-webhook-live:
    description: "Zoho webhook URL for live environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send card notification to Zoho Cliq
      shell: bash
      env:
        # ✅ FIXED: Use inputs instead of secrets context
        ZOHO_WEBHOOK_PREVIEW: ${{ inputs.zoho-webhook-preview }}
        ZOHO_WEBHOOK_STAGE: ${{ inputs.zoho-webhook-stage }}
        ZOHO_WEBHOOK_LIVE: ${{ inputs.zoho-webhook-live }}
      run: |
        chmod +x $GITHUB_ACTION_PATH/notify.sh
        $GITHUB_ACTION_PATH/notify.sh \
          "${{ inputs.message }}" \
          "${{ inputs.environment }}" \
          "${{ inputs.status }}" \
          "${{ inputs['service-type'] }}" \
          "${{ inputs.preview-url }}" \
          "${{ inputs.stage-url }}" \
          "${{ inputs.live-url }}"
