name: 'Notify'
description: 'Sends notifications to Zoho Cliq'

inputs:
  webhook-url:
    description: 'Zoho Cliq webhook URL'
    required: true
  message:
    description: 'Message to send'
    required: true
  environment:
    description: 'The environment (preview, stage, live)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Send notification
      shell: bash
      run: |
        # Escape special characters in the message
        ESCAPED_MESSAGE=$(echo '${{ inputs.message }}' | sed 's/"/\\"/g')
        
        # Determine theme based on environment
        if [ "${{ inputs.environment }}" = "live" ]; then
          THEME="modern-inline"
        else
          THEME="basic"
        fi

        curl -X POST "${{ inputs.webhook-url }}" \
          -H "Content-Type: application/json" \
          -d '{
            "text": "'"$ESCAPED_MESSAGE"'",
            "card": {
              "title": "Deployment Notification",
              "theme": "'"$THEME"'",
              "thumbnail": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
              "sections": [{
                "title": "Details",
                "data": [
                  {"Repository": "'"$GITHUB_REPOSITORY"'"},
                  {"Environment": "'"${{ inputs.environment }}"'"},
                  {"Commit": "'"$GITHUB_SHA"'"},
                  {"Author": "'"$GITHUB_ACTOR"'"},
                  {"Branch/Tag": "'"$GITHUB_REF_NAME"'"}
                ]
              }],
              "buttons": [{
                "label": "View Deployment",
                "action": {
                  "type": "open.url",
                  "url": "'"$GITHUB_SERVER_URL"'/'"$GITHUB_REPOSITORY"'/actions/runs/'"$GITHUB_RUN_ID"'"
                }
              }]
            }
          }'
