name: "Zoho Cliq Notification"
description: "Send deployment notifications to Zoho Cliq"
author: "CloudOps One"
inputs:
  webhook-url:
    description: "Zoho Cliq webhook URL"
    required: true
  message:
    description: "Notification message text"
    required: true
  environment:
    description: "Deployment environment (preview/stage/live)"
    required: true
  status:
    description: "Deployment status (success/failure)"
    required: true
  service-type:
    description: "Type of service (e.g., admin, api, client)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Send Zoho Cliq notification
      shell: bash
      run: |
        chmod +x $GITHUB_ACTION_PATH/notify.sh
        $GITHUB_ACTION_PATH/notify.sh \
          "${{ inputs.webhook-url }}" \
          "${{ inputs.message }}" \
          "${{ inputs.environment }}" \
          "${{ inputs.status }}" \
          "${{ inputs.service-type }}"
