name: 'Docker Push Action'
description: 'Push Docker image to Harbor registry'
inputs:
  image_name:
    description: 'Name of the Docker image'
    required: true
    default: 'server-irai-yoga-v1-ci'
  docker_tag:
    description: 'Docker tag to use'
    required: true
  harbor_registry:
    description: 'Harbor registry URL'
    required: true
  harbor_username:
    description: 'Harbor username'
    required: true
  harbor_password:
    description: 'Harbor password'
    required: true

runs:
  using: "composite"
  steps:
    - name: Verify Harbor credentials
      shell: bash
      run: |
        if [ -z "${{ inputs.harbor_registry }}" ]; then
          echo "❌ HARBOR_REGISTRY is not set"
          exit 1
        fi
        if [ -z "${{ inputs.harbor_username }}" ]; then
          echo "❌ HARBOR_USERNAME is not set"
          exit 1
        fi
        if [ -z "${{ inputs.harbor_password }}" ]; then
          echo "❌ HARBOR_PASSWORD is not set"
          exit 1
        fi
        echo "✅ All Harbor credentials are configured"

    - name: Download Docker image
      uses: cloudops-one/download-artifact@v4
      with:
        name: docker-image
        path: .

    - name: Load Docker image
      shell: bash
      run: |
        docker load -i docker-image.tar
        echo "Loaded images:"
        docker images --format "table {{.Repository}}\t{{.Tag}}\t{{.Size}}"

    - name: Login to Harbor Registry
      shell: bash
      run: |
        HARBOR_REG="${{ inputs.harbor_registry }}"
        HARBOR_USER="${{ inputs.harbor_username }}"
        HARBOR_PASS="${{ inputs.harbor_password }}"
        
        echo "🔐 Logging into Harbor registry: $HARBOR_REG"
        echo "$HARBOR_PASS" | docker login $HARBOR_REG --username $HARBOR_USER --password-stdin

    - name: Tag and push Docker image
      shell: bash
      run: |
        IMAGE_NAME="${{ inputs.image_name }}"
        DOCKER_TAG="${{ inputs.docker_tag }}"
        HARBOR_REG="${{ inputs.harbor_registry }}"
        
        LOCAL_IMAGE="$IMAGE_NAME:$DOCKER_TAG"
        REMOTE_IMAGE="$HARBOR_REG/$IMAGE_NAME:$DOCKER_TAG"
        
        echo "📦 Tagging image:"
        echo "  Local:  $LOCAL_IMAGE"
        echo "  Remote: $REMOTE_IMAGE"
        docker tag $LOCAL_IMAGE $REMOTE_IMAGE
        
        echo "🚀 Pushing image: $REMOTE_IMAGE"
        docker push "$REMOTE_IMAGE"
        
        echo "✅ Image pushed successfully!"

    - name: Logout from Harbor Registry
      if: always()
      shell: bash
      run: |
        HARBOR_REG="${{ inputs.harbor_registry }}"
        docker logout $HARBOR_REG || echo "Logout failed or already logged out"
