apiVersion: apps/v1
kind: Deployment
metadata:
  name: DEPLOYMENT_NAME_PLACEHOLDER
  namespace: irai-yoga-v1-preview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: SELECTOR_APP_PLACEHOLDER
  template:
    metadata:
      labels:
        app: SELECTOR_APP_PLACEHOLDER
    spec:
      containers:
        - name: SERVER_CONTAINER_PLACEHOLDER
          image: harbor.cloudops.terv.pro/portal-irai-yoga/admin:TAG_PLACEHOLDER
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "250m"
              memory: 512Mi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
      imagePullSecrets:
        - name: harbor-secret
