name: 'Install Security Tools'
description: 'Installs security scanning tools (Trivy, Snyk)'

runs:
  using: 'composite'
  steps:
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget apt-transport-https gnupg lsb-release curl
      shell: bash

    - name: Install Trivy
      run: |
        # Download and install Trivy directly (more reliable than apt)
        wget -qO - https://github.com/aquasecurity/trivy/releases/download/v0.49.1/trivy_0.49.1_Linux-64bit.deb
        sudo dpkg -i trivy_0.49.1_Linux-64bit.deb || sudo apt-get install -f -y
        trivy --version
        echo "✅ Trivy installed successfully"
      shell: bash

    - name: Install Snyk
      run: |
        # Install Snyk via npm (already available in GitHub runners)
        npm install -g snyk
        snyk --version
        echo "✅ Snyk installed successfully"
      shell: bash
