name: "Build Java Project"
description: "Builds Java projects with Maven or Gradle"

inputs:
  build-tool:
    description: "Build tool (maven or gradle)"
    required: true
  java-version:
    description: "Java version"
    required: true
  cache:
    description: "Enable caching"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        java-version: ${{ inputs.java-version }}
        distribution: "temurin"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gradle/caches
        key: ${{ runner.os }}-${{ inputs.build-tool }}-${{ hashFiles('**/*.gradle*', '**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-${{ inputs.build-tool }}-

    - name: Build with Maven
      if: ${{ inputs.build-tool == 'maven' }}
      run: mvn clean install

    - name: Build with Gradle
      if: ${{ inputs.build-tool == 'gradle' }}
      run: ./gradlew build
